Id: nvisionative.nvQuickSite
Version: 2.0.0
Name: nvQuickSite
Publisher: nvisionative
License: GPL3
LicenseUrl: https://github.com/nvisionative/nvQuickSite/blob/v2.0.0/nvQuickSite/LICENSE.md
AppMoniker: nvQuickSite
Tags: dnn, dotnetnuke, installer, website, cms
Description: nvQuickSite is a desktop installation app for DNN, the world's most popular ASP.NET-based CMS. This app allows you to easily install DNN onto any environment that meets the minimum system requirements for DNN to be installed.
Homepage: https://www.nvquicksite.com/
Installers:
  - Arch: Neutral
    Url: https://github.com/nvisionative/nvQuickSite/releases/download/v2.0.0/nvQuickSite_v2.0.0_Installer.msi
    Sha256: D84FCAAE5B2A3FB75D02219DFB6F2EBA0D9E376D9AF3F81C15E71CE9B38E60DA
    InstallerType: msi